<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLxwnimd\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLxwnimd/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerLxwnimd.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerLxwnimd\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerLxwnimd\appProdProjectContainer([
    'container.build_hash' => 'Lxwnimd',
    'container.build_id' => '3ec1b8a1',
    'container.build_time' => 1614326932,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLxwnimd');
